### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by allenhs** [kanttouchthis/text_generation_webui_xtts#1]
Here is the issue upon trying to load it:

2023-11-19 12:19:09 ERROR:Failed to load the extension "text-generation-webui-xtts".
Traceback (most recent call last):
  File "/home/Username/AI/text-generation-webui/modules/extensions.py", line 36, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1
    import extensions.text-generation-webui-xtts.script

**Comment by allenhs** [comment]
Update, I got it to work by renaming the extension folder from "text-generation-webui-xtts" to "text_generation_webui_xtts".

**Comment by erew123** [comment]
I had a few other bumps too. Have put issue/fix on here which you may need to check :)

**Comment by kanttouchthis** [comment]
i changed the repo name to fix the issue
