### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'no_stream'

### ISSUE THREAD

**Issue by dazinator** [kanttouchthis/text_generation_webui_xtts#15]
I am seeinng the following error when the extension is loading and I wondered if anyone had any pointers? coqui_tts extension is working ok.

I noted when I installed TTS like this `pip install TTS --no-dependencies` the extension would not load and I saw an error about `torchaudio` not being installed. I do not see `torchaudio` in requirements.txt either. So I basically did a `pip install TTS` which did install `torchaudio` and other stuff, but didn't fully complete because of `numpy` discrepencies (probably as expected as I guess thats why you advise using `--no-dependencies` ?)
```
 INFO     Loading the extension "text_generation_webui_xtts"     
 ERROR    Failed to load the extension                           
                          "text_generation_webui_xtts".                          
 Traceback (most recent call last):
   File "/home/app/text-generation-webui/modules/extensions.py", line 36, in load_extensions
     exec(f"import extensions.{name}.script")
   File "<string>", line 1, in <module>
  File "/home/app/text-generation-webui/extensions/text_generation_webui_xtts/script.py", line 12, in <module>
     streaming_state = shared.args.no_stream
 AttributeError: 'Namespace' object has no attribute 'no_stream'
```

**Comment by dazinator** [comment]
Hmm I "solved" this by removing the `streaming_state` variable entirely from the script so it was several lines.

I wonder if an upstream extension is able to remove it or something (I am not familiar with python code)
