### ISSUE TITLE
errror today new install of text-generation-webui and TTS

### ISSUE THREAD

**Issue by kalle07** [kanttouchthis/text_generation_webui_xtts#19]
cd extensions
git clone https://github.com/kanttouchthis/text_generation_webui_xtts
cd text_generation_webui_xtts
pip install -r requirements.txt
pip install TTS --no-dependencies
"all without errors"

start_windows.bat
12:11:23-410072 INFO     Loading the extension "gallery"
12:11:23-410072 INFO     Loading the extension "text_generation_webui_xtts"
12:11:23-418610 ERROR    Could not import the requirements for 'text_generation_webui_xtts'. Make sure to install the
                         requirements for the extension.

                         * To install requirements for all available extensions, launch the
                           update_wizard script for your OS and choose the B option.

                         * To install the requirements for this extension alone, launch the
                           cmd script for your OS and paste the following command in the
                           terminal window that appears:

                         Linux / Mac:

                         pip install -r extensions/text_generation_webui_xtts/requirements.txt --upgrade

                         Windows:

                         pip install -r extensions\text_generation_webui_xtts\requirements.txt --upgrade

12:11:23-418610 ERROR    Failed to load the extension "text_generation_webui_xtts".
Traceback (most recent call last):
  File "e:\text-generation-webui\modules\extensions.py", line 37, in load_extensions
    extension = importlib.import_module(f"extensions.{name}.script")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\text-generation-webui\installer_files\env\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "e:\text-generation-webui\extensions\text_generation_webui_xtts\script.py", line 1, in <module>
    from TTS.api import TTS
ModuleNotFoundError: No module named 'TTS'

Running on local URL:  http://127.0.0.1:7860

**Comment by kalle07** [comment]
sry now installed in environment:


12:39:11-578928 INFO     Loading the extension "gallery"
12:39:11-578928 INFO     Loading the extension "text_generation_webui_xtts"
12:39:21-727333 ERROR    Failed to load the extension "text_generation_webui_xtts".
Traceback (most recent call last):
  File "e:\text-generation-webui\modules\extensions.py", line 37, in load_extensions
    extension = importlib.import_module(f"extensions.{name}.script")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\text-generation-webui\installer_files\env\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "e:\text-generation-webui\extensions\text_generation_webui_xtts\script.py", line 12, in <module>
    streaming_state = shared.args.no_stream
                      ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'no_stream'

Running on local URL:  http://127.0.0.1:7860

**Comment by kalle07** [comment]
alltalk no probelm   ;) 

https://github.com/erew123/alltalk_tts?tab=readme-ov-file
